version: '3.7'

services:
  mysql:
    container_name: inf21dw1g02-mysql
    image: inf21dw1g02-mysql
    build:
      context: .
      dockerfile: ./dockerfile.mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: 1234567
      # MYSQL_DATABASE: movies
    networks:
      - inf21dw1g02-network
    ports:
      - 3306:3306
  app:
    depends_on:
      - mysql
    container_name: inf21dw1g02-app
    image: inf21dw1g02-app
    build:
      context: .
      dockerfile: ./dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 8080:8080
    networks:
      - inf21dw1g02-network

networks:
  inf21dw1g02-network:
 